#!/usr/bin/env bash
# Update the package list and install Nginx
apt-get update -y
apt-get install -y nginx

# Create an HTML file with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Ensure Nginx is running
service nginx start

# Redirect port 80 to localhost to serve content using sysctl
echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
sysctl -p /etc/sysctl.conf

