#!/usr/bin/env bash
# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
# Make sure nginx is running
sudo service nginx start
# Configure nginx to listen to port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
# Set up the Hello World page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# Restart nginx
sudo service nginx restart
