#!/usr/bin/env bash
# Update the package list and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Create an HTML file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Remove the default Nginx configuration
sudo rm /etc/nginx/sites-enabled/default

# Create a new Nginx configuration that serves your page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Enable the new configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo service nginx restart
