#!/usr/bin/env bash
# This script installs Nginx and configures a redirection from /redirect_me to a specified URL

# Update packages and Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Remove the default configuration
sudo rm /etc/nginx/sites-enabled/default

# Create a configuration file for the redirection
echo "server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/redirection

# Enable the configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/redirection /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo service nginx restart
