#!/usr/bin/env bash
# This script installs Nginx and configures a custom 404 page

# Update packages and Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Remove the default configuration
sudo rm /etc/nginx/sites-enabled/default

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Create a configuration file for the custom 404 page
echo "server {
    listen 80;
    server_name _;
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /usr/share/nginx/html;
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/custom_404

# Enable the configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo service nginx restart
