#!/usr/bin/env bash

# Update the system packages
sudo apt-get update

# Install Nginx if it's not already installed
sudo apt-get install -y nginx

# Create a custom 404 error page with the desired content
sudo sh -c 'echo "Ceci n'"'"'est pas une page" > /usr/share/nginx/html/custom_404.html'

# Create a custom Nginx configuration file for the custom 404 page
sudo tee /etc/nginx/sites-available/custom_404 <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /usr/share/nginx/html;
    index index.html index.htm;

    server_name 52.3.250.55;

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOF

# Create a symbolic link to enable the custom configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test the Nginx configuration
sudo nginx -t

# Reload Nginx to apply the changes
sudo systemctl reload nginx
