#!/usr/bin/env bash
# shellcheck disable=SC2154
# Check if nginx is installed
if ! command -v nginx &> /dev/null
then
    # Install nginx
    sudo apt-get -y update
    sudo apt-get -y install nginx
fi
# Make sure nginx is running
sudo service nginx start
# Configure nginx to listen to port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
# Set up the Hello World page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# Get the hostname
HOSTNAME=$(hostname)
# Add the custom header to all location blocks in the default site configuration
sudo sed -i "/location /a\        add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
# Restart nginx
sudo service nginx restart
