#!/usr/bin/env bash
# This script checks if Nginx is running and listening on port 80, and configures it if necessary
#remove the default Nginx configuration
rm /etc/nginx/sites-enabled/default
# configure Nginx to use port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart Nginx
service nginx restart
