#!/usr/bin/env bash
# This script ensures Nginx is running and listening on port 80
systemctl is-active --quiet nginx || {
    # Configure Nginx to use port 80
    rm /etc/nginx/sites-enabled/default
    ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
    # Restart Nginx
    systemctl restart nginx
}
