#!/usr/bin/env bash
# This script ensures Nginx is running and listening on port 80
# configure Nginx to use port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart Nginx
service nginx restart
#Kill nginx process
kill "$(pgrep 'nginx' | head -1)"
