#!/usr/bin/env bash
# Update /etc/hosts file and restarts the server

sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/g' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
sudo service networking restart
