#!/usr/bin/env bash
# Stop nginx service
service nginx stop

# Open nginx.conf file
NGINX_CONF='/etc/nginx/nginx.conf'

# Change user from 'root' to 'nginx'
sed -i 's/user root;/user nginx;/' $NGINX_CONF

# Change the listen directive to use port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default

# Start nginx service
service nginx start
