#!/usr/bin/env bash
# This script configures the container to run nginx as the nginx user and listen on port 8080

# Stop nginx
service nginx stop

# Change the user in the nginx configuration file
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Change the listen directive to listen on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default

# Start nginx
service nginx start
